name: clarity_gov
description: Sistema de Fiscalización de Transporte - La Joya Avanza

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  
  # Storage & Preferences
  shared_preferences: ^2.2.2
  
  # Camera & Images
  image_picker: ^1.0.4
  
  # Date & Time formatting
  intl: ^0.18.1
  
  # PDF Generation
  pdf: ^3.10.7
  printing: ^5.11.1
  
  # Bluetooth & Printing
  flutter_bluetooth_serial: ^0.4.0
  esc_pos_utils: ^1.1.0
  
  # Material Design
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
  
  # Fonts
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700